apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-kubernetes
spec:
  package: xpkg.upbound.io/crossplane-contrib/provider-kubernetes:v0.13.0
  runtimeConfigRef:
    name: provider-dns-config
---
apiVersion: pkg.crossplane.io/v1beta1
kind: DeploymentRuntimeConfig
metadata:
  name: provider-dns-config
spec:
  deploymentTemplate:
    spec:
      selector: {}
      template:
        spec:
          dnsConfig:
            nameservers:
              - 1.1.1.1
            options:
            - name: ndots
              value: "2"
          containers: []